name: UT-report

on:
  push:
    branches: ['master']

jobs:
  generate-Another-report:
    name: Generate another UT Report
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        run: npm install

      - name: Generate report
        run: npm run test

      - name: Display structure of downloaded files
        if: always()
        run: ls

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: UT-reports